Implement button.
js-tasks-ru/htmlcss-20210916_protagoras-from-abdera pull request #4
Opened 2021-09-24 16:07 UTC by IncompletableFuture

2021-09-24 16:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-26 11:42 UTC, GSemikozov requested changes

2021-09-26 11:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.card__button {
здесь мы описываем отдельный независимый переиспользуемый компонент, не элемент карточки, поэтому - везде надо заменить .card__button на .button

2021-09-26 11:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    line-height: 18.75px;
дробные пиксели лучше не использовать

2021-09-26 11:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
еще, вместо такого курсора, рекомендуется указывать pointer-events: none (установит курсор в default)

2021-09-26 11:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
pointer пусть будет всегда на кнопке .button по умолчанию

2021-09-26 11:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
можно сразу в .button указать

2021-09-26 12:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-26 13:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-26 13:56 UTC, IncompletableFuture commented on 03-lection1/01-button/button.css
> +.card__button {
Поменял название этого класса и его сопутствующих.

2021-09-26 13:56 UTC, IncompletableFuture commented on 03-lection1/01-button/button.css
> +    line-height: 18.75px;
Округлил до целого значения.

2021-09-26 13:57 UTC, IncompletableFuture commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
Вынес стили в класс .button.

2021-09-26 13:57 UTC, IncompletableFuture commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
Сделано.

2021-09-26 13:57 UTC, IncompletableFuture commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
Сделано.

2021-09-28 19:20 UTC, GSemikozov approved these changes

2021-09-28 19:20 UTC, merged